name: Build Releases
on:
  push:
    tags:
      - "*.*.*"

env:
  CARGO_TERM_COLOR: always

jobs:
  build-cross:
    runs-on: ubuntu-latest
    env:
      RUST_BACKTRACE: full
    strategy:
      matrix:
        target:
          - x86_64-unknown-linux-gnu
          - x86_64-unknown-linux-musl
          - x86_64-unknown-linux-gnu:centos # for CentOS 7 which uses Glibc 2.17
          - aarch64-unknown-linux-gnu
          - aarch64-unknown-linux-musl

    steps:
      - uses: actions/checkout@v3
      - uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
          target: ${{ matrix.target }}
          override: true
        if: ${{ matrix.target != 'x86_64-unknown-linux-gnu:centos' }}
      - uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
          target: x86_64-unknown-linux-gnu
          override: true
        if: ${{ matrix.target == 'x86_64-unknown-linux-gnu:centos' }}
      - name: use CentOS 7 special base image if necessary
        if: ${{ matrix.target == 'x86_64-unknown-linux-gnu:centos' }}
        run: echo "CROSS_CONFIG=Cross.centos7.toml" >> $GITHUB_ENV
      - uses: actions-rs/cargo@v1
        with:
          use-cross: true
          command: build
          args: --release --target ${{ matrix.target }}
      - name: Rename artifacts and compress
        run: |
          cd target/${{ matrix.target }}/release
          zip atc_router_${{ matrix.target }}-cdylib.zip libatc_router.so
          zip atc_router_${{ matrix.target }}-staticlib.zip libatc_router.a
      - name: Upload Github Assets
        uses: softprops/action-gh-release@v1
        with:
          files: target/${{ matrix.target }}/release/*.zip
          prerelease: ${{ contains(github.ref, '-') }}
